wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1634537220
    t:
      1:
      - 2
      - 3
      3:
      - 16
      4: 3.7.12
      5: 0.12.4
      8:
      - 1
      - 5
architecture:
  desc: null
  value: Yazeed
batch_size:
  desc: null
  value: 64
dataset:
  desc: null
  value: KHATT
epochs:
  desc: null
  value: 350
learning_rate:
  desc: null
  value: 0.001
loss_function:
  desc: null
  value: CTC
